#!/bin/bash
 
salida=`sudo arp-scan -I eth0 --localnet > arp.txt`
while read LINEA
do 
        ip=`echo $LINEA | cut -f 1 -d "."`
        if [ $ip = "192" ] 2>/dev/null
        then
                mac=`echo $LINEA | cut -f 2 -d " "`
                identificar_mac1=`echo $mac | cut -f 1 -d ":"`
                identificar_mac2=`echo $mac | cut -f 2 -d ":"`
                if [ $identificar_mac1 == "00" ]
                then
                        if [ $identificar_mac2 = "0c" ]
                        then
                                ipfinal=`echo $LINEA | cut -f 1 -d " "`
                                echo "$ipfinal | $mac -> Vmare"
                        fi
                fi
                if [ $identificar_mac1 == "08" ]
                then
                        if [ $identificar_mac2 = "00" ]
                        then
                                ipfinal=`echo $LINEA | cut -f 1 -d " "`
                                echo "$ipfinal | $mac -> VirtualBox"
                        fi
                fi

        fi

done < arp.txt
sudo rm  arp.txt
